services:
  # Backend (Django)
  backend:
    build:
      context: ./duty-chart-backend
      dockerfile: Dockerfile
    container_name: duty-chart-backend
    volumes:
      - ./duty-chart-backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  # Redis Broker
  redis:
    image: redis:7-alpine
    container_name: duty-chart-redis
    ports:
      - "6379:6379"

  # Celery Worker
  celery_worker:
    build:
      context: ./duty-chart-backend
      dockerfile: Dockerfile
    container_name: duty-chart-celery-worker
    command: celery -A config worker --loglevel=info
    volumes:
      - ./duty-chart-backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - ./.env
    depends_on:
      - backend
      - db
      - redis

  # Celery Beat
  celery_beat:
    build:
      context: ./duty-chart-backend
      dockerfile: Dockerfile
    container_name: duty-chart-celery-beat
    command: celery -A config beat --loglevel=info
    volumes:
      - ./duty-chart-backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - ./.env
    depends_on:
      - backend
      - db
      - redis

  # Database (Postgres)
  db:
    image: postgres:15
    container_name: duty-chart-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  # Frontend (React + Nginx)
  frontend:
    build:
      context: ./duty-chart-frontend
      dockerfile: Dockerfile
    container_name: duty-chart-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
